version: '3.1'

services:
  postgres:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: go-hex
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  
  mongodb:
    image: mongo:6.0.8
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

  jaeger:
    image: docker.io/jaegertracing/all-in-one:1.47.0
    ports:
      - "16686:16686"
      - "14268:14268"
      - "6832:6832"
      - "6831:6831"

volumes:
  postgres:
  mongodb: